### ISSUE TITLE
[Chapter 08] (스프링 시큐리티로 로그인/로그아웃 회원가입 구현하기) 예제코드 관련 이슈

### ISSUE THREAD

**Issue by 2eungwoo** [shinsunyoung/springboot-developer#10]
교재에 나와있는 예제 코드 중에서,
 public SecurityFilterChain filterChain() 메서드에서
.formLogin(), .and(), .logout(), .csrf() 메서드가 deprecated 되었다고 합니다. 

공식 문서를 보고 수정해보려했으나 도저히...ㅠ
도움 주시면 감사하겠습니다..!!

스프링 시큐리티 공식문서 링크입니다
https://docs.spring.io/spring-security/site/docs/current/api/deprecated-list.html

**Comment by shinsunyoung** [comment]
https://github.com/shinsunyoung/springboot-developer/issues/5 이 이슈 참고해주시면 될 것 같습니다! 혹시나 이후에도 해결되지 않는다면 알려주세요. 감사합니다!
