### ISSUE TITLE
[Chapter 07] 수정/생성에서 버튼이 동작하지 않습니다.

### ISSUE THREAD

**Issue by dudxor4587** [shinsunyoung/springboot-developer#11]
newarticle 페이지 까지는 보여지는데 그 페이지에서 수정이나, 등록 버튼을 눌러도 아무런 응답이 없습니다.
책에 나와있는 코드를 그대로 다 작성했는데 크롬 개발자 창에서도 아무것도 안뜨는 것으로 봐서 아예 동작을 하지 않는 것 같습니다.
도움 부탁드립니다

**Comment by shinsunyoung** [comment]
안녕하세요! [수정/등록] 버튼을 눌렀을 때 intelliJ에서 아무런 로그도 뜨지 않나요?
아니면 작성하신 코드를 올려주시면 제가 확인 후에 더 정확한 답변 드릴 수 있을 것 같습니다!

**Comment by dudxor4587** [comment]
깃에 올려져있던 코드로 비교해서 해결했습니다!
감사합니다!
