### ISSUE TITLE
[Chapter 04] 4.3제대로 테스트 코드 작성해보기

### ISSUE THREAD

**Issue by sjmoon00** [shinsunyoung/springboot-developer#12]
책의 순서대로 진행하던 도중 오류가 해결이 안되어 질문 드립니다.
1
Member savedMember = memberRepository.save(new Member(1L, "홍길동")); 
이 곳에서 new Member 부분에 'Member()' cannot be applied to '(long, java.lang.String)' 라고 나오면서 오류가 해결이 안됩니다.
마우스를 가져가면 Expected 0 arguments but found 2라고 나옵니다.

2
테스트 코드 마지막부분
.andExpect(jsonPath("$[0].id").value(savedMember.getId()))
.andExpect(jsonPath("$[0].name").value(savedMember.getName()));
getId()와 getName()메서드도 Cannot resolve method 'getId' in 'Member'
라면서 해결이 안됩니다.

**Comment by shinsunyoung** [comment]
안녕하세요! Member가 책에서 만든 객체(me.shinsunyoung.springbootdeveloper 패키지의 Member.java)가 아니라 다른 Member 객체가 임포트 된 것 같습니다. Member 쪽 코드 구문을 지웠다 다시 작성하면서 책에서 만든 객체로 임포트되는지 확인해보시겠어요?!

**Comment by sjmoon00** [comment]
<img width="734" alt="image" src="https://github.com/shinsunyoung/springboot-developer/assets/68841095/5c762287-d6f3-4da7-9cb6-44de6665aa6b">

캡쳐에서 첫번째 Member를 선택한건지 확인해보라는 말씀이라면 제대로 한 것 같습니다.

혹시나 하고 깃허브 코드를 맨 첫번째줄을 제외하고 그대로 복사해봐도 같은 증상이 나타나네요..

**Comment by shinsunyoung** [comment]
혹시 전체 코드를 올려두신 곳이 있으실까요?

**Comment by sjmoon00** [comment]
intellij를 재설치 하니까 해결됐네요!
