### ISSUE TITLE
[Chapter 0] gradle 설정 중 오류가 이해되지 않아서 질문드립니다

### ISSUE THREAD

**Issue by raik1353** [shinsunyoung/springboot-developer#14]
책을 구매해 입문하고 있습니다 초반 gradle 설정 중 오류가 나는데 검색을 해보아도 무엇이 잘못 되었는지 모르겠습니다
혹시 해결 가능할까요?
![asdasdas](https://github.com/shinsunyoung/springboot-developer/assets/140177872/bb3f27f7-ba84-4f4e-8972-9728213c564b)

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\������\IdeaProjects\springboot-developer\build.gradle.kts' line: 9

* What went wrong:
Script compilation errors:

  Line 09: sourceCompatibility = "17"
           ^ Unresolved reference: sourceCompatibility

  Line 18: test {
           ^ Expression 'test' cannot be invoked as a function. The function 'invoke()' is not found

  Line 18: test {
           ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
               public val SourceSetContainer.test: NamedDomainObjectProvider<SourceSet> defined in org.gradle.kotlin.dsl
               public val TaskContainer.test: TaskProvider<Test> defined in org.gradle.kotlin.dsl

  Line 19:     useJUnitPlatform()
               ^ Unresolved reference: useJUnitPlatform

4 errors

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

**Comment by shinsunyoung** [comment]
gradle 파일이 kts 파일로 되어있는 것 같은데요! build.gradle.kts -> build.gradle 로 바꿔서 다시 시도해보시겠어요?

**Comment by raik1353** [comment]
답변 감사합니다! 혹시 build.gradle.kts -> build.gradle 어떻게 바꾸어야 할까요?

**Comment by raik1353** [comment]
bulid system을 제대로 설정하지 못했기 때문이네요...답변 너무 감사합니다!!
