### ISSUE TITLE
[Chapter 11] EB 502에러

### ISSUE THREAD

**Issue by XIO1016** [shinsunyoung/springboot-developer#15]
책과 똑같이 EB에 배포했는데,, 막상 url로 접속하면 502에러가 뜹니다...

구글링해보아도 포트문제라고 나오는데, 이미 책에 적힌대로 SERVER_PORT = 5000으로 설정한 상태입니다..

환경도, 인스턴스도 정상적으로 돌아가고 있고요

에러 로그 출력해보면 눈에 띄는 에러는 다음이 있습니다
2023/08/24 03:33:28 [warn] 7195#7195: could not build optimal types_hash, you should increase either types_hash_max_size: 1024 or types_hash_bucket_size: 64; ignoring types_hash_bucket_size
2023/08/24 04:10:02 [error] 9847#9847: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.20.237, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host:

**Comment by shinsunyoung** [comment]
안녕하세요! web.stdout.log의 로그를 볼 수 있을까요? 어플리케이션이 제대로 실행했는지 보면 좋을 것 같습니다.
[로그] - [마지막 100줄 or 전체]로 다운로드 받으신 뒤 확인하실 수 있습니다!

**Comment by XIO1016** [comment]
안녕하세요, 로그 첨부합니다!

[web.stdout.log](https://github.com/shinsunyoung/springboot-developer/files/12447884/web.stdout.log)

**Comment by shinsunyoung** [comment]
파일 내용이 비어있는데 한 번만 다시 확인 부탁드립니다!! 🙇

**Comment by XIO1016** [comment]
앗 죄송합니다!..
[web.stdout.log](https://github.com/shinsunyoung/springboot-developer/files/12464352/web.stdout.log)

**Comment by shinsunyoung** [comment]
```
Aug 27 11:52:32 ip-172-31-2-132 web[283667]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
Aug 27 11:52:32 ip-172-31-2-132 web[283667]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Aug 27 11:52:32 ip-172-31-2-132 web[283667]: #011at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-j-8.0.32.jar!/:8.0.32]
Aug 27 11:52:32 ip-172-31-2-132 web[283667]: #011at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-j-8.0.32.jar!/:8.0.32]
Aug 27 11:52:32 ip-172-31-2-132 web[283667]: #011at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:824) ~[mysql-connector-j-8.0.32.jar!/:8.0.32]
Aug 27 11:52:32 ip-172-31-2-132 web[283667]: #011at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444) ~[mysql-connector-j-8.0.32.jar!/:8.0.32]
Aug 27 11:52:32 ip-172-31-2-132 web[283667]: #011at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-j-8.0.32.jar!/:8.0.32]
Aug 27 11:52:32 ip-172-31-2-132 web[283667]: #011at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-j-8.0.32.jar!/:8
```

mysql 관련 에러가 났네요! DB 연결 설정쪽을 확인해보시면 좋을 것 같습니다.
