### ISSUE TITLE
[Chapter 08] Security 에러 문의

### ISSUE THREAD

**Issue by skyleedevzero86** [shinsunyoung/springboot-developer#17]
안녕하세요 저자님.
저자님 도서를 가지고 8장 시큐리티 학습하고 있는 개발자입니다.
security 쪽에 에러가 나는데 문의드려도 괜찮을까요??
왜 이미지와 같은 에러가 날까요??
스프링 버전은 3.1.3입니다.
감사합니다.

![image](https://github.com/shinsunyoung/springboot-developer/assets/81811670/156a2ed5-0d36-4296-bff2-d110f58cd637)

package com.suervey.blog.config;

import com.suervey.blog.service.UserDetailService;
import lombok.RequiredArgsConstructor;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityCustomizer;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.web.SecurityFilterChain;
import static org.springframework.boot.autoconfigure.security.servlet.PathRequest.toH2Console;
@RequiredArgsConstructor
@Configuration
public class SecurityConfig {

    private final UserDetailService userService;
    @Bean
    public WebSecurityCustomizer configure() {
        return (web) -> web.ignoring()
                .requestMatchers(toH2Console())
                .requestMatchers("/static/**");
    }
    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        return http
                .authorizeRequests()
                .requestMatchers("/login", "/signup", "/user").permitAll()
                .anyRequest().authenticated()
                .and()
                .formLogin()
                .loginPage("/login")
                .defaultSuccessUrl("/articles")
                .and()
                .logout()
                .logoutSuccessUrl("/login")
                .invalidateHttpSession(true)
                .and()
                .csrf().disable()
                .build();
    }

    @Bean
    public AuthenticationManager authenticationManager(HttpSecurity http, BCryptPasswordEncoder bCryptPasswordEncoder, UserDetailService userDetailService) throws Exception {
        return http.getSharedObject(AuthenticationManagerBuilder.class)
                .userDetailsService(userService)
                .passwordEncoder(bCryptPasswordEncoder)
                .and()
                .build();
    }
    @Bean
    public BCryptPasswordEncoder bCryptPasswordEncoder() {
        return new BCryptPasswordEncoder();
    }

}

**Comment by skyleedevzero86** [comment]
저 소스가 문제가 없는 소스인 것 같은데..
다른 방법으로 설정할 수 있을까요?

**Comment by skyleedevzero86** [comment]
한 가지 더 궁금한 게 있는데요.
2.7.3 버전에는 아래와 같이 작성을 하였는데.
3.x 버전에 사용한다고 하면 어떻게 하는 게 좋을까요?..

@Configuration
@RequiredArgsConstructor
@EnableWebSecurity
@EnableMethodSecurity
public class SecurityConfig {
    private final CustomOAuthUserService customUserTypesOAuth2UserService;
    private final JwtSuccessHandler jwtSuccessHandler;
    private final FormUserDetailService formUserDetailService;
    private final FormAuthenticationProvider formAuthenticationProvider;
    private final JwtAuthenticationFilter jwtAuthenticationFilter;

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        http
                .csrf().disable()
                .headers().frameOptions().disable()
                .and()

                .userDetailsService(formUserDetailService)
                .authenticationProvider(formAuthenticationProvider)

                // URL 인가
                .authorizeRequests()
                .antMatchers("/**", "/users/login", "/users/register","/app/**",
                        "/css/**", "/images/**", "/js/**", "/h2-console/**", "/login/proc").permitAll()
                    .antMatchers("/api/**", "/answers/**", "/surveys/**").hasRole(Role.USER.name())
                    .anyRequest().authenticated()
                .and()

                // form Login
                .formLogin()
                    .loginPage("/users/login")
                    .loginProcessingUrl("/login/proc")
                    .usernameParameter("username")
                    .passwordParameter("password")
                    .failureUrl("/users/login?error=true")
                    .successHandler(jwtSuccessHandler)
                .and()

                // Logout
                .logout()
                    .logoutUrl("/app/users/logout")
                    .logoutSuccessUrl("/users/login")
                .and()

                //
                .oauth2Login()
                .userInfoEndpoint()
                .userService(customUserTypesOAuth2UserService);

        http
                // AnonymousAuthenticationFilter 이후 실행
                .addFilterBefore(jwtAuthenticationFilter, ExceptionTranslationFilter.class);

        return http.build();
    }
}

**Comment by skyleedevzero86** [comment]
기존의 예제는 h2를 바라보고 있지만 DB를 oracle이나 mysql로 변경할 경우 어떻게 해야 할까요?
그레이들에 h2는 삭제하고
runtimeOnly 'com.mysql:mysql-connector-j' 이것을 추가한 상태입니다.

mysql은 8.x 버전을 사용하고 있습니다.

**Comment by shinsunyoung** [comment]
시큐리티 에러 관련해서는 #8 확인하시면 도움이 될 것 같습니다!

> 기존의 예제는 h2를 바라보고 있지만 DB를 oracle이나 mysql로 변경할 경우 어떻게 해야 할까요?

책에서는 mysql을 사용하기 위해 `implementation 'mysql:mysql-connector-java'` dependency를 추가했습니다!
사용하고자 하는 DBMS마다 의존성을 제공해주기 때문에 적절한 의존성으로 교체해주시면 될 것 같습니다.

**Comment by LeeKyeongYong** [comment]
oauth2로그인에서
 http.oauth2Login(oauth2Login -> oauth2Login
                .loginPage("/login")
                .authorizationEndpoint(authorizationEndpoint -> authorizationEndpoint
                        .authorizationRequestRepository(oAuth2AuthorizationRequestBasedOnCookieRepository()))
                .successHandler(oAuth2SuccessHandler())
                .userInfoEndpoint(userInfoEndpoint -> userInfoEndpoint
                        .userService(oAuth2UserCustomService)));
                        
                        이것을 사용하지만  일반 로그인에서는 어떻게 사용하나요?
