### ISSUE TITLE
[Chapter 11] 새로운 AWS UI에서 Elastic Beanstalk 환경 생성 (p. 318)

### ISSUE THREAD

**Issue by shinsunyoung** [shinsunyoung/springboot-developer#18]
AWS의 Elastic Beanstalk 환경 생성 UI가 이전과 달라져서 어떻게 바꿔야할지 모르겠는 분들을 위해 가이드를 작성합니다. 아래 순서를 따라해주세요. (p. 318)

# Step 1. IAM 역할 생성
1. AWS > IAM > [역할](https://us-east-1.console.aws.amazon.com/iamv2/home?region=ap-northeast-2#/roles) > 역할 만들기를 눌러주세요.
![image](https://github.com/shinsunyoung/springboot-developer/assets/42836576/ad297d8f-3d25-4d82-afa9-c56f394b4a4d)

2. 신뢰할 수 있는 엔티티 유형으로는 [AWS 서비스]를, 사용 사례는 [EC2]를 선택합니다.
![image](https://github.com/shinsunyoung/springboot-developer/assets/42836576/0199a6c8-273c-45bc-91e7-e36684655129)

3. 권한 추가 메뉴에서 아래 3개의 권한을 추가해주세요.
- AWSElasticBeanstalkMulticontainerDocker
- AWSElasticBeanstalkWebTier
- AWSElasticBeanstalkWorkerTier
![image](https://github.com/shinsunyoung/springboot-developer/assets/42836576/0e64e4c0-7bbf-4846-a2fd-0872016f035a)

4. 역할 이름은 [aws-elasticbeanstalk-ec2-role]로 적어주시고, 신뢰할 수 있는 엔티티와 권한이 잘 추가되었는지 확인한 후에 역할을 생성합니다.
* 다른 이름을 사용해도 무방하나 EB 생성 시에 선택할 수 있도록 기억해주세요
![image](https://github.com/shinsunyoung/springboot-developer/assets/42836576/03b97cc4-e635-4ff0-83c2-a85d43424437)

# Step 2. EB 생성
1. AWS > [Elastic Beanstalk](https://ap-northeast-2.console.aws.amazon.com/elasticbeanstalk/home?region=ap-northeast-2#/environments) > 환경 > 환경 생성을 눌러주세요.

![image](https://github.com/shinsunyoung/springboot-developer/assets/42836576/5420ae02-5fd0-492b-b99b-bf60ce464142)

2. 환경 구성에서는 아래와 같이 선택해주세요
- 애플리케이션 이름 : springboot-developer
- 플랫폼 : Java (Corretto 17)

나머지는 기본 값으로 두고 다음을 눌러주세요.

3. 서비스 액세스 구성에서 아래와 같이 선택해주세요
- 서비스 역할 : 새 서비스 역할 생성 및 사용 > [aws-elasticbeanstalk-service-role] 작성 (다른 이름을 사용해도 무방)
- EC2 인스턴스 프로파일 : [aws-elasticbeanstalk-ec2-role] 선택

![image](https://github.com/shinsunyoung/springboot-developer/assets/42836576/f71a413e-7fec-4506-9249-fa45a8fae71d)

4. 검토 단계로 건너뛰기 후 [제출] 선택

# Step 3. 확인
제공해준 도메인 주소로 접속했을 때 샘플 애플리케이션 페이지가 잘 나오는지 확인합니다.
![image](https://github.com/shinsunyoung/springboot-developer/assets/42836576/478ece6c-fc98-4058-a6c9-b7e389c9bf44)

**Comment by JasonSong97** [comment]
안 그래도 진짜 필요했었는데 정말 감사합니다!! ㅠㅠ

**Comment by Oyisbe** [comment]
너무 감사합니다 !
