### ISSUE TITLE
[Chapter 09] TokenProviderTest에서 테스트를 찾을 수 없다고 되는데 어떤 문제가 있는지 알 수 있을까요?

### ISSUE THREAD

**Issue by raik1353** [shinsunyoung/springboot-developer#19]
깃허브에 진행한 것 올려두었습니다..

**Comment by shinsunyoung** [comment]
안녕하세요 이슈를 닫으셨는데 헤결된거라고 이해하면 될까요? 아직 해결이 안 됐거나, 추가 질문이 있으면 이슈 다시 열어주시면 감사드리겠습니다! (아니라면 무시해주세요)
