### ISSUE TITLE
[Chapter 11] 구성->데이터베이스에서 엔드포인트 접속이 되지 않습니다.

### ISSUE THREAD

**Issue by YMJ936** [shinsunyoung/springboot-developer#21]
https://github.com/shinsunyoung/springboot-developer/issues/18 여기서 설명해주신 대로 설정을 마친 후 환경을 생성하고 데이터베이스를 생성했습니다.
![image](https://github.com/shinsunyoung/springboot-developer/assets/133292703/c98f3018-1964-41ed-9a8c-a608fe232000)
그러나 구성에서는 탭에서는 엔드포인트를 찾을 수 없었습니다.
![image](https://github.com/shinsunyoung/springboot-developer/assets/133292703/d825e156-071a-4afa-b3a1-31cda5c447e3)
편집을 눌러서 들어가니 엔드포인트가 있었지만 클릭해도 데이터베이스 관리 페이지로 이동되지 않고 빈 페이지만 뜹니다.
![image](https://github.com/shinsunyoung/springboot-developer/assets/133292703/01167498-4930-4232-9c79-a9df5811e567)
![image](https://github.com/shinsunyoung/springboot-developer/assets/133292703/ae2a0e7e-2814-4b84-9d9a-cb756e751b9d)
혹시나 나머지 설정을 완료하면 해결이 될까 싶어서 AWS 사이트 검색창에 RDS를 검색해 나머지 설정을 마치고 jar파일 배포까지 진행해보았으나 502오류가 발생했습니다. 어떻게든 혼자 해결해보려 끙끙대다 도저히 방법을 찾을 수가 없어서 이렇게 질문 올립니다. ㅠㅠ

**Comment by shinsunyoung** [comment]
안녕하세요.
EB에서 생성한 데이터 베이스 = 말씀해주신 RDS에서 생성된 데이터베이스입니다! 
324쪽 내용부터 쭉 따라하셨고 database navigator에서 동작 확인까지 하셨는데 502가 뜨는 문제인걸까요?

**Comment by na03266** [comment]
> 안녕하세요. EB에서 생성한 데이터 베이스 = 말씀해주신 RDS에서 생성된 데이터베이스입니다! 324쪽 내용부터 쭉 따라하셨고 database navigator에서 동작 확인까지 하셨는데 502가 뜨는 문제인걸까요?

저도 똑같은 문제가 있었는데, RDS 메뉴로 들어가서 활성화 된 DB에 직접 세팅을 해주니까 되긴했었습니다.

**Comment by YMJ936** [comment]
324쪽 내용부터 쭉 따라하고 database navigator까지 갔으나 문제가 발생했습니다. 이전에 제가 어떻게든 해결해보고자 잘 모르는 데도 불구하고 이것저것 눌러서 database navigator 연결까지는 성공한 적이 있었으나 일주일이 넘게 지나서 잘 기억이 나지 않습니다 ㅠㅠ 그리고 그 때 502 오류가 발생했기 때문에 현재는 제가 잘 모르는 부분은 건드리지 않고 있습니다.

DB식별자가 링크 형태가 아니어서 클릭해서 이동하지 못했습니다. 그래서 오른쪽 하단에 VPC 보안그룹을 클릭해 들어갔습니다.
![image](https://github.com/shinsunyoung/springboot-developer/assets/133292703/6d3a6f8c-f9f2-4b33-bdc2-31862ab73c06)

이후 보안 그룹 3개 중 아래의 두개는 유형과 소스를 변경하자 아래 스크린 샷에 나온 오류가 뜨면서 규칙 저장이 불가능 했고 맨 위에 있는 보안 그룹만 규칙 저장이 가능했습니다. 그래서 맨 위에 있는 보안 그룹만 규칙을 바꾸고 진행했습니다.
![image](https://github.com/shinsunyoung/springboot-developer/assets/133292703/790bff01-d751-4591-b3e7-da6483efd66f)
![image](https://github.com/shinsunyoung/springboot-developer/assets/133292703/70f49029-4916-4a9f-851a-5eaadd9aa030)

database navigator를 설치한 후에 Host, Port, Uesr, Password를 책에서 설명해주신 대로 입력하고 테스트커넥션 버튼을 눌렀으나 오류가 발생했습니다.
![image](https://github.com/shinsunyoung/springboot-developer/assets/133292703/f497ae8d-70f4-4df7-b19c-70f917ee4256)

**Comment by na03266** [comment]
저... 삽질하다가 알아낸거 정리해서 블로그글로 남겨놨는데 한번 보시겠어요?
https://blog.naver.com/na03266/223189598873

**Comment by YMJ936** [comment]
블로그 보고 해결했습니다 감사합니다!!

**Comment by Cbulls** [comment]
저도 502 뜨는 똑같은 문제가 있었는데요, 위에 올려주신 블로그 보고 해결했습니다! 😄

업데이트, 모니터링 및 로깅 부분의 environment properties에서 SPRING_SECURITY_OAUTH2_CLIENT 속성 3개를 지우고, 
대신에  RDS_HOSTNAME, RDS_PORT, RDS_DB_NAME, RDS_USERNAME, RDS_PASSWORD 집어넣으니 성공했습니다.

왜 이게 성공하는지는 잘 모르겠지만, 성공해서 기쁘네요 ㅎㅎ
혹시나 아시는 분 있으시면 설명 부탁드립니다~

**Comment by na03266** [comment]
> 저도 502 뜨는 똑같은 문제가 있었는데요, 위에 올려주신 블로그 보고 해결했습니다! 😄
> 
> 업데이트, 모니터링 및 로깅 부분의 environment properties에서 SPRING_SECURITY_OAUTH2_CLIENT 속성 3개를 지우고, 대신에 RDS_HOSTNAME, RDS_PORT, RDS_DB_NAME, RDS_USERNAME, RDS_PASSWORD 집어넣으니 성공했습니다.
> 
> 왜 이게 성공하는지는 잘 모르겠지만, 성공해서 기쁘네요 ㅎㅎ 혹시나 아시는 분 있으시면 설명 부탁드립니다~

원래 AWS 정책은 책 내용이 맞는데 이후 보안의 이유로 변경된 정책때문에 저처럼 입력하셔야하는것입니다.
인바운드 규칙 편집한 내용은 아무래도 책의 내용은 본인 IP만 허용하는데, 제가 아무리해도 안되길래...  모든 IP를 허용해주는걸로 바꾸어서 진행한 부분인점... 때문에 보안에는 조금 더 취약합니다.

**Comment by WhyBreakMe** [comment]
NaHwangje님 내용을 쭈욱 따라가봤는데요, 결국 whitelabel error 500 엔딩 났습니다 ㅜㅜ
서버 문제 같은데요, 계속 기다리기만 해도 되는 부분일까요?

**Comment by shinsunyoung** [comment]
@WhyBreakMe 님, 제가 이 코멘트를 이제 봤는데 아직 같은 현상이 발생하시는걸까요?
그러면 새 이슈로 에러 로그와 좀 더 상세한 설명 주시면 도움 드릴 수 있을 것 같습니다!

**Comment by na03266** [comment]
@WhyBreakMe 님, 혹시 그레이들 최신화 안하고 배포누르신건 아니신가요? 임포트 경로가 잘못되어있을 수도 있습니다. 그리고 테스트 코드까지 오류가 없어야만 정상배포 되니... 꼭 확인해주세요.

**Comment by WhyBreakMe** [comment]
@NaHwangje 임포트 경로는 한번 다시 봐보겠습니다. 그레이들 최신화는 즉각즉각 시행하였고, 테스트 코드는 아무 문제 없이 돌아가는 것을 3번 확인했습니다.
Whitelabel error 뜨는건 아마도 화면을 띄울 페이지 경로 문제가 아닌가 하는 얘기를 들은 기억이 있어서, 임포트 경로는 다시 점검해봐야 할 것 같긴 합니다.
