### ISSUE TITLE
[Chapter 06] 책 141페이지 03단계 h2-Console 을 통해접속을 할수가 없어 문의 드립니다. 

### ISSUE THREAD

**Issue by MacTechIN** [shinsunyoung/springboot-developer#22]
<img width="1043" alt="Screenshot 2023-09-19 at 8 31 04 PM" src="https://github.com/shinsunyoung/springboot-developer/assets/63564804/f7f6fd40-ecf8-4d19-ade6-57a722320e47">

안녕하세요 h4-console에 접속을 하려면 패스워드가 설정이 되어 있어야 하는데 yml에 

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 123456

  h2:
    console:
      enable: true
설정하고도 접속이 패스워드가 안맞는건지 .섭속이 되지 않아서 문의 드립니다. 감사합니다.

**Comment by shinsunyoung** [comment]
JDBC URL이 잘못 설정되어 있습니다~!
