### ISSUE TITLE
[Chapter 10] TokenProvider에서 Cannot pass null or empty values to constructor 에러가 뜨면서 글이 등록되지 않습니다

### ISSUE THREAD

**Issue by Cbulls** [shinsunyoung/springboot-developer#23]
안녕하세요! OAuth2를 활용해서 구글 로그인에 성공하고 글을 작성하는 과정에서 계속해서 "등록 실패했습니다."라는 팝업과 함께 실패해서 질문 남깁니다.

먼저 개발자 도구를 열어서 확인한 결과 액세스 토큰과 리프레쉬 토큰 모두 이상 없이 잘 들어있습니다.
디버거로 코드의 거의 모든 줄에 브레이크 포인트를 걸어서 확인한 결과 밑에 코드 중  org.springframework.security.core.userdetails.User(claims.getSubject
                (), "", authorities), token, authorities); 에서 문제가 발생하면서 Cannot pass null or empty values to constructor 오류와 함께 더 이상 실행되지 않더군요. 

혹시 패스워드를 넣지 않아서 생기는 문제일까 해서 아예 빈 문자열을 빼고 null로 바꿔도 문제가 생기더군요.
yml 파일에서 패스워드를 지정한 뒤에 구글 로그인으로 회원가입을 한 유저는 패스워드를 넣고 그 패스워드를 활용하는게 나을까요?
답변해주시면 정말 감사드리겠습니다 ㅎㅎ

```
public Authentication getAuthentication(String token) {
        Claims claims = getClaims(token);
        Set<SimpleGrantedAuthority> authorities = Collections.singleton(new SimpleGrantedAuthority("ROLE_USER"));

        return new UsernamePasswordAuthenticationToken(new org.springframework.security.core.userdetails.User(claims.getSubject
                (), "", authorities), token, authorities);
    }
```

**Comment by shinsunyoung** [comment]
안녕하세요! 제가 전체 코드를 확인할 수 없어 확답은 드리지 못하지만 말씀해주신 내용을 보았을 때 
"Cannot pass null or empty values to constructor" 라고하면 User 객체를 만들 때 빈 값이나 null값이 들어가서 에러가 나는 것으로 보이는데요.

실제로 org.springframework.security.core.userdetails.User 객체를 만드는 생성자를 확인해보면 아래와 같은 코드를 확인하실 수 있습니다.

```
        public User(String username, String password, Collection<? extends GrantedAuthority> authorities) {
		this(username, password, true, true, true, true, authorities);
	}

	public User(String username, String password, boolean enabled, boolean accountNonExpired,
			boolean credentialsNonExpired, boolean accountNonLocked,
			Collection<? extends GrantedAuthority> authorities) {
		Assert.isTrue(username != null && !"".equals(username) && password != null,
				"Cannot pass null or empty values to constructor");
		this.username = username;
		this.password = password;
		// ... 생략 ....
	}
```

여기에서 오류 로그가 나는 조건을 보면
```
// 유저 이름: null, 빈값
// 패스워드: null
// 일 때 에러가 난다.
Assert.isTrue(username != null && !"".equals(username) && password != null,
				"Cannot pass null or empty values to constructor");
```

인데요. 패스워드는 빈 값을 허용하지만 유저 이름은 빈 값을 허용하지 않습니다. 그런데 빈 값(혹은 null값)이 들어가서 에러가 난 것으로 보입니다. 
결론적으로 `claims.getSubject()`값이 잘 들어가 있는지 확인해보시면 좋을 것 같습니다~!

**Comment by Cbulls** [comment]
답변 정말 감사드립니다 ㅎㅎ 조언해주신대로 코드를 봐보니 `claims.getSubject()` 가 null 값으로 들어온게 확인이 되었고, 토큰 생성 과정을 자세히 보니 `Jwt.builder().setSubject(user.getEmail())` 코드가 빠져 있었습니다! 다시 한번 감사드립니다 ㅎㅎ

아 그리고 하면서 궁금한 사항인데, 혹시 실무에서도 위와 같은 OAuth 상황에서 User 객체를 만들 때 비밀번호를 빈 값을 넣나요?
혹시나 보안적인 이슈가 있지 않을까 해서 여쭤드립니다!

**Comment by shinsunyoung** [comment]
넵 OAuth를 사용하면 비밀번호가 어플리케이션으로 제공되지 않고 사용자의 데이터에 접근할 수 있는 토큰만 제공하기 때문에 사용자의 비밀번호를 직접 저장하지 않습니다!

**Comment by Cbulls** [comment]
친절하게 답변해주셔서 정말 감사드립니다 ㅎㅎ
