### ISSUE TITLE
[Chapter 06] 책 141페이지 03단계 h2-Console 접속 자체가 안됩니다.

### ISSUE THREAD

**Issue by agacap** [shinsunyoung/springboot-developer#25]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sun Oct 15 22:53:12 KST 2023
There was an unexpected error (type=Not Found, status=404).

라고뜨며

build.gradle 에 이런걸 추가하면 뜬다고해서 넣었더니
화면은 뜹니다만, 책 화면내용과 같이 JDBC URL 등을 넣어도 접속이 되지 않습니다.

dependencies {
    implementation 'org.springframework.boot:spring-boot-devtools'

**Comment by shinsunyoung** [comment]
안녕하세요. 혹시 application.yml에 h2 console 관련 설정이 추가되어 있는 상태이신가요?
https://github.com/shinsunyoung/springboot-developer/blob/main/chapter6/src/main/resources/application.yml#L10-L12

**Comment by agacap** [comment]
네 추가되었습니다.. github의 코드 그대로 적용했습니다.

**Comment by shinsunyoung** [comment]
깃허브에 코드 올려봐주시면 확인해보겠습니다! 🙇

**Comment by shinsunyoung** [comment]
2주 이상 업데이트가 없어 close 해두겠습니다. 아직 해결이 안 됐거나, 추가 질문이 있으면 이슈 다시 열어주시면 감사드리겠습니다!
