### ISSUE TITLE
[Chapter 10] 코드작성후 실행 시 오류가 발생합니다

### ISSUE THREAD

**Issue by melaminn38** [shinsunyoung/springboot-developer#26]
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-10-23T11:06:10.864+09:00 ERROR 9776 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Method filterChain in org.example1.springbootdeveloper1.config.WebOAuthSecurityConfig required a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' in your configuration.

실행 시 이런 오류가뜨면서 실행이 안됩니다
어디가 틀렸는지 찾을수 가 없어서 문의드립니다.. 깃허브 : https://github.com/melaminn38/blog1.git

**Comment by shinsunyoung** [comment]
깃허브에 application.yml 파일이 안 올라와있네요! https://github.com/melaminn38/blog1/tree/main/main/resources 

만약 민감값때문에 올리지 않으신거라면 아래 링크를 참고하여 application.yml 파일을 다시 한 번 확인해주세요! 특히 yml 파일 depth에 영향을 받기 때문에 depth대로 잘 작성했는지 확인해보시면 좋을 것 같습니다.
https://github.com/shinsunyoung/springboot-developer/blob/main/chapter10/src/main/resources/application.yml

**Comment by melaminn38** [comment]
감사합니다. 해결했습니다. 어딘가에 오타가있었던거 같습니다.
