### ISSUE TITLE
92p. Assertions.assertEquals(a + b, sum); 기대값, 실제값 순서

### ISSUE THREAD

**Issue by limvik** [shinsunyoung/springboot-developer#3]
안녕하세요.

책 잘 읽고 있습니다. 좋은 책 써주셔서 감사합니다. 

제가 잘못 생각한건가 해서 오탈자 신고로 올리려고 했더니, 출판사 홈페이지 오탈자 신고가 막혀있어서 여기 올려봅니다.

92p. JUnit 설명하는 부분에서 인수로 기대값과 실제값이 사용되는데, 책에는 아래와 같이 코드가 작성되어 있습니다.

Assertions.assertEquals(a + b, sum);

그런데 기대하고 있는 값이 sum 이고, 틀릴 수 있는 실제 값이 a + b가 아닌가 해서 문의 드립니다.

Assertions.assertEquals(sum, a + b);

---

몇 가지 오탈자

68p. 에 3번 4번 문제가 동일하게 작성돼있는데 정오표에는 반영이 안돼있습니다.
85p. 프레젠테이션 계층은 HTTP 요청을 받고 비즈니스 **계층로** 전송합니다. -> 계층**으**로
86p. 2번 문제 ... **계층로** -> 계층**으**로

한 글자, 한 글자 꼼꼼히 보고 있습니다. ㅎㅎ 감사합니다.

**Comment by shinsunyoung** [comment]
안녕하세요! 제보해주셔서 감사합니다. 🙇‍♀️
말씀해주신대로 assertEquals()는 expected(기대값), actual(실제값)의 순서대로 들어가기 때문에 
Assertions.assertEquals(sum, a + b); 으로 변경되는게 맞습니다.

오탈자&문제도 모두 반영해두어 2쇄때 적용될 예정입니다. 감사합니다!
https://docs.google.com/spreadsheets/d/1mhsju1QRhbFmslkxD1cwxmjIkOqSW5MpZpHGeozcA6E/edit?usp=sharing
