### ISSUE TITLE
[Chapter 03] import 오류 해결 후에도 생기는 오류

### ISSUE THREAD

**Issue by jasonpark112** [shinsunyoung/springboot-developer#30]
package me.jihooo.springbootdeveloper;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class TestService {
    @Autowired
    MemberRepository memberRepository;

    public List<Member> getAllMembers() {
        return memberRepository.findAll();
    }
}
여기서 계속 findAll() 메소드가 빨간 줄이 나와요 !!

그리고,

package me.jihooo.springbootdeveloper;

import org.springframework.stereotype.Repository;

@Repository
public interface MemberRepository extends JpaRepository<Member, Long> {
}

JpaRepository 이거 역시 빨간 줄 계속나오는데 원인을 모르겠습니다 ㅠ

그 외에도

package me.jihooo.springbootdeveloper;

import com.fasterxml.jackson.annotation.JsonTypeId;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Getter
@Entity

public class Member {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false)
    private Long id;

    @Column(name = "name", nullable = false)
    private String name;
}

여기서 @Entity 등등 여러 군데에서 빨간 줄입니다. !! 해결할 방법이 있을까요 ?

**Comment by shinsunyoung** [comment]
`@service`, `@repository`, `@getter`, `@entity`, `@id`, `@column` 모두 어노테이션 앞 글자가 대문자가 되어야 합니다.

**Comment by jasonpark112** [comment]
> `@service`, `@repository`, `@getter`, `@entity`, `@id`, `@column` 모두 어노테이션 앞 글자가 대문자가 되어야 합니다.

어 이거는 옮기면서 자동으로 소문자가 된거 같아요 실제로는 대문자로 다 했는데 현재 안 되는 상황이에요 ㅠ

**Comment by shinsunyoung** [comment]
깃허브에 작성하신 코드 올려주시면 확인해보겠습니다~!

**Comment by jasonpark112** [comment]
> 깃허브에 작성하신 코드 올려주시면 확인해보겠습니다~!

넵 !! 주말인데 죄송합니다 ㅎㅎ ㅠ

https://github.com/jasonpark112/errorQuestion

**Comment by shinsunyoung** [comment]
코드를 프로젝트 전체를 올려주셔야할 것 같습니다! 그런데 지금 생각하기로는 오류 나는 곳이 lombok 쪽이라면 lombok 플러그인을 설치하지 않아 생기는 문제일 수도 있을 것 같은데요.
Setting > Plugins > Marketplace에서 "lombok" 검색 후 다운로드 & 인텔리제이 재시작 해보시고 그래도 똑같이 안 되면 프로젝트 전체를 깃허브에 올려주실 수 있으실까요?
![image](https://github.com/shinsunyoung/springboot-developer/assets/42836576/8895c03a-8e36-4d1d-9fa1-1652a3d0c580)

**Comment by jasonpark112** [comment]
> 코드를 프로젝트 전체를 올려주셔야할 것 같습니다! 그런데 지금 생각하기로는 오류 나는 곳이 lombok 쪽이라면 lombok 플러그인을 설치하지 않아 생기는 문제일 수도 있을 것 같은데요. Setting > Plugins > Marketplace에서 "lombok" 검색 후 다운로드 & 인텔리제이 재시작 해보시고 그래도 똑같이 안 되면 프로젝트 전체를 깃허브에 올려주실 수 있으실까요? ![image](https://user-images.githubusercontent.com/42836576/282279931-8895c03a-8e36-4d1d-9fa1-1652a3d0c580.png)

설치 안 되어 있어서 했는데도 그대로인거 같아요 !! 

링크 보냅니다!

https://github.com/jasonpark112/project1

**Comment by shinsunyoung** [comment]
의존성에 JPA 추가가 안되어 있습니다~!
https://github.com/shinsunyoung/springboot-developer/blob/main/chapter3/build.gradle

여기 참고하셔서 의존성 맞추고 import 다시 시도해보시면 제대로 작동할 것 같아요

**Comment by jasonpark112** [comment]
> 의존성에 JPA 추가가 안되어 있습니다~! https://github.com/shinsunyoung/springboot-developer/blob/main/chapter3/build.gradle
> 
> 여기 참고하셔서 의존성 맞추고 import 다시 시도해보시면 제대로 작동할 것 같아요

제가 빼먹은게 있었군요 !! 드디어 cmd + enter가 먹힙니다 ㅠㅠ 주말인데 정성껏 답변해주신거 너무 감사합니다 ㅎㅎ
