### ISSUE TITLE
[Chapter 4] 책 102페이지 04단계  TestControllerTest가 Run중 에러가 나고있습니다.

### ISSUE THREAD

**Issue by shimson7** [shinsunyoung/springboot-developer#32]
![image](https://github.com/shinsunyoung/springboot-developer/assets/101376930/eafa8229-9c7a-4e2e-a9dd-7ddf261f7a8e)

위와 같은 에러가 떠서 코드를 복붙해 봤는데도 에러가 나고 있어 어떻게 해결해야 할지 모르겠습니다.

build.gradle과 gradle wrapper.properties도 따라했고, build.gradle의 group만 제 것으로 변경해놨습니다.

**Comment by shimson7** [comment]
![image](https://github.com/shinsunyoung/springboot-developer/assets/101376930/684c24b8-39a6-4e2d-a4da-eb9696f1737e)

Gradle 설정도 똑같이 했는데 어떤게 문제일까요...?

**Comment by shinsunyoung** [comment]
안녕하세요! https://cherish-it.tistory.com/20 해당 링크 참고하셔서 해결해보시겠어요?

**Comment by shimson7** [comment]
gradle 버전을 최신 버전으로 하니 오류 해결 됐습니다!
https://gradle.org/releases/
