### ISSUE TITLE
[Chapter 07] Article 에 EntityListeners 선언이 빠져있습니다.

### ISSUE THREAD

**Issue by linusix** [shinsunyoung/springboot-developer#33]
날짜가 업데이트 안되서 git 소스를 봤더니 EntityListeners 가 선언되어 있는데 책에는 없네요.

**Comment by shinsunyoung** [comment]
맞습니다. 해당 부분을 책에도 넣었어야 했는데 실수로 빠트렸고, 다음 인쇄 시에는 코드 하이라이트 표시 되게 반영할 예정입니다. 제보해주셔서 감사합니다!! 🙏🙏
