### ISSUE TITLE
[Chapter 09] p.241 java.lang.IllegalArgumentException: secret key byte array cannot be null or empty.

### ISSUE THREAD

**Issue by LimdaeIl** [shinsunyoung/springboot-developer#34]
토큰 관련 테스트 작성하다가 테스트 전부 다 실패하고 IllegalArgumentException 예외가 발생해서 질문 남기기 직전에 해결했습니다. 
왠지 저랑 비슷한 실수하신 분들 있을 것 같아서 이슈에 남깁니다.
application.yml 파일 안에 secret_key 속성값을 너무 짧게 입력해서 생기는 IllegalArgumentException 예외로, 최소 4글자 이상 작성해야 정상적으로 모든 테스트 통과할 수 있습니다.

## secret_key 수정 전
![image](https://github.com/shinsunyoung/springboot-developer/assets/131642334/78bfa31a-9e34-4b18-9ba8-07ee97be1db7)

## secret_key 수정 후
![image](https://github.com/shinsunyoung/springboot-developer/assets/131642334/b406803f-ee14-49aa-ad75-2f524a8c162c)

**Comment by shinsunyoung** [comment]
안녕하세요! 공유해주셔서 감사합니다.  해당 내용 개정판에서도 챙길 수 있도록 하겠습니다!!  🙏 🙏
