### ISSUE TITLE
[Chapter 08] 너무 감사합니다. 작가님 책 보고 많은 도움을 받고 있습니다.  질문 요청드립니다.

### ISSUE THREAD

**Issue by elite177719** [shinsunyoung/springboot-developer#38]
안녕하세요.
해당 책을 보며 스프링부트 기본을 공부하고 있습니다.
다만 요청사항이 있습니다.
앞에 8장까지 내용으로 구축된 로그인 사이트와 9장 jwt를 연결하는 방법을 구현해보려고 하는데 이부분 연결하는 방법을 코드로 구현해주시면 큰 도움이 됩니다.

감사합니다.

**Comment by shinsunyoung** [comment]
안녕하세요~! 좋은 말씀 감사합니다. 

> 앞에 8장까지 내용으로 구축된 로그인 사이트와 9장 jwt를 연결하는 방법을 구현해보려고 하는데 이부분 연결하는 방법을 코드로 구현해주시면 큰 도움이 됩니다.

8장 로그인 사이트와 9장에서 배운 jwt를 사용해 인증 하는 방법은 10장에서 OAuth를 사용하며 연결합니다!
