### ISSUE TITLE
[Chapter 04] 작가님 안녕하세요 테스트 코드에 대해서 질문이 있습니다.

### ISSUE THREAD

**Issue by smilejakdu** [shinsunyoung/springboot-developer#39]
단위 테스트를 진행하게 될때
SpringBootTest 어노테이션을 사용하지않고 , 
@ExtendWith(MockitoExtension.class)
를 클래스 위에 애너테이션을 적용한 뒤에 

사용할 mock 객체를 @InjectMock 으로 불러오고 그 객체안에서 주입해서 사용하는 객체들을 @Mock 으로 불러와서 사용했습니다. 

하지만 책에서는 @Autowired 를 애너테이션을 사용하더라구요.
그 이유와 어떤차이점으로 @Autowired 를 사용해서 테스트를 진행하셨나요 ??

**Comment by shinsunyoung** [comment]
안녕하세요! 답변이 너무 늦어 죄송합니다 ㅠㅠ 제가 알림을 놓치고 있었네요.
우선 mockito에 대해 깊게 다루지 않았기 때문에 Mocking을 최소화하고 싶었고, H2를 사용하기 때문에 `@Autowired` 를 사용해 실제 데이터를 생성/삭제해도 문제가 없기 때문에 별도의 모킹을 하지 않았습니다. Controller ~ Repository 까지 직접 실행 하며 문제가 없는지 검증하기 위한 목적도 있었고요) 말씀하신대로 완전한 단위테스트를 하기 위해 `@InjectMock`를 사용해도 무방합니다. 더 질문 있으시면 알려주세요! 감사합니다 🙏
