### ISSUE TITLE
Chapter08 Security 문제에서 회원가입 로직이 작동하지 않고 있습니다.

### ISSUE THREAD

**Issue by drakejin** [shinsunyoung/springboot-developer#4]
# 문제
회원가입이 작동하지 않음.

# 원인
- request 로 사용하는 AddUserRequest 에 값이 들어가지 않고 있음.
- Lombok Annotation에서 값을 주입할 수 있게 인자가 있는 생성자를 두거나 Setter를 둬야함.

# 코드의 위치 및 코드 수정 제안

Chapter08

``` java
package me.shinsunyoung.springbootdeveloper.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@NoArgsConstructor
// ++ @AllArgsConstructor <- 추가 되어야 하는 annotation
public class AddUserRequest {
    private String email;
    private String password;
    private String auth;
}
```

**Comment by shinsunyoung** [comment]
안녕하세요! 답변이 늦어 죄송합니다 😭
책에서는 @Setter 어노테이션이 존재하기 때문에 에러가 나지 않지만, 예제코드와 sync가 맞춰지지 않아 발생했습니다.
현재는 sync해둔 상태입니다! 제보해주셔서 감사합니다 🙏

https://github.com/shinsunyoung/springboot-developer/blob/main/chapter8/src/main/java/me/shinsunyoung/springbootdeveloper/dto/AddUserRequest.java
