### ISSUE TITLE
[Chapter 09] jwt임포트 문제에 대해서

### ISSUE THREAD

**Issue by parkkkkjuneHyeon** [shinsunyoung/springboot-developer#42]
dependencies {
    .........
    testAnnotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.projectlombok:lombok'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'
}

현재 의존성이 추가 됐는데 
Jwts.builder()
                .setHeaderParam(Header.TYPE, Header.JWT_TYPE)
                .setIssuer(jwtProperties.getIssuer())
                .setExpiration(expiry)
                .setSubject(user.getEmail())
                .claim("id", user.getId())
                .signWith(SignatureAlgorithm.HS256, jwtProperties.getSecretKey())
                .compact();

Jwts가 io.jsonwebtoken 임포트가 안돼어서 오류가 납니다. 어떤것이 문제인지 잘모르겠습니다.

**Comment by shinsunyoung** [comment]
안녕하세요. 1. spring boot 버전이 3.0.2 버전이 맞는지 먼저 확인해주시면 좋을 것 같고(책의 코드는 3.0.2 버전 기준으로 작성되었기 때문에 3.0.2이 아닌 다른 버전을 사용하면 라이브러리 버전이 바뀌어야 제대로 작동한다거나 사용법이 달라질 수 있기 때문입니다.), 2. jwt 의존성은 implementation 'io.jsonwebtoken:jjwt:0.9.1' 만 추가하면 됩니다.

FYI. https://github.com/shinsunyoung/springboot-developer/blob/main/chapter11/build.gradle
