### ISSUE TITLE
[Chapter 06] 6장 update 메소드

### ISSUE THREAD

**Issue by kwangsus** [shinsunyoung/springboot-developer#43]
@Transactional
    public Article update(long id, UpdateArticleRequest request) {
        Article article = blogRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("not found: " + id));

        article.update(request.getTitle(), request.getContent());
        log.info(article.toString());
        return article;

    }

article을 수정하는 update는 클라이언트에게 전송만 되고 db에는 반영되지 않는것 아닌가요?

**Comment by shinsunyoung** [comment]
JPA를 사용하면 엔티티 내용이 변경된 것을 추적하여 DB를 업데이트 해줍니다. JPA의 변경 감지에 대해 찾아보시면 좋을 것 같습니다!

**Comment by kwangsus** [comment]
감삼당 @Transactional 추가설명이 없어서 몰랏네요
