### ISSUE TITLE
[Chapter 11] 구글 로그인 오류

### ISSUE THREAD

**Issue by DungBeetle0618** [shinsunyoung/springboot-developer#45]
승인된 리디렉션 URI 주소 삽입 시 프로덕션 단계에서 http 주소 삽입 불가 현상이 나타납니다.

![image](https://github.com/shinsunyoung/springboot-developer/assets/148679054/d06fe8cb-ea4a-41bc-a522-6cdd07cb97d3)

 https: 를 입력하면 저장은 되지만 이후에
 login 창까지는 잘 뜨고 구글 로그인을 누르면 차단 됩니다.

![image](https://github.com/shinsunyoung/springboot-developer/assets/148679054/44ec298c-b781-4035-9e3c-a7beb02e7395)

**Comment by shinsunyoung** [comment]
안녕하세요. 저는 http 를 사용하는데도 해당 에러가 안 뜨는데 이상하네요 🤔
![image](https://github.com/shinsunyoung/springboot-developer/assets/42836576/54823f07-f0e0-402e-92b2-f3367eae6cc2)

혹시 입력하신 URI 전문을 알 수 있을까요?

**Comment by DungBeetle0618** [comment]
http://Springboot-developer-ver2-env.eba-tdzwt4vt.ap-northeast-2.elasticbeanstalk.com/login/oauth2/code/google
이렇게  입력했습니다.
우선 저의 문제 같으니 다시 한 번 해보겠습니다 감사해여!!
-----Original Message-----

**Comment by shinsunyoung** [comment]
흠 이상하네요 🤔 혹시나 싶어 제 계정에서 넣어봤는데 경고 없이 잘 뜨네요 ㅠㅠ
![image](https://github.com/shinsunyoung/springboot-developer/assets/42836576/48b0edb9-374f-4134-a317-3ed98607da27)

아니면 직접 도메인을 구매해 프로토콜을 https 로 바꿔 다시 시도하는 방법도 있을 것 같습니다!

**Comment by dav1n9** [comment]
http 를 사용하는 경우 게시 상태를 "테스트"로 변경해야 합니다.
[API 및 서비스 -> OAuth 동의화면] 에 들어가서 게시 상태를[테스트]로 변경하고 URI를 추가해 보세요.
https url을 사용하는 프로젝트만 [프로덕션 단계] 에서 URI 를 추가할 수 있는 것 같습니다.

**Comment by shinsunyoung** [comment]
기본 설정이 바뀌었나보네요 ㅠ.ㅠ @DungBeetle0618 님 위 방법대로 한 번 시도해봐주시겠어요? 일단 이 이슈는 close 해두겠습니다.
