### ISSUE TITLE
[부록 B] 378p, 예외처리 테스트 중 에러

### ISSUE THREAD

**Issue by 9uiopa** [shinsunyoung/springboot-developer#47]
안녕하세요,
BlogApiControllerTest 에서
HttpRequestMethodNotSupportedException    ###예외에 대한 테스트 코드 실행시 발생하는 에러입니다.

![1](https://github.com/shinsunyoung/springboot-developer/assets/22972372/75097aec-384c-4a26-830f-9833b4c05287)
![2](https://github.com/shinsunyoung/springboot-developer/assets/22972372/cf768a35-cb4e-4140-9de0-dc6c4e9966af)

사진에서 보면 print 된 response에 Body가 없기 때문에(body 외에도 조금씩 값이 다른 부분이 있음) 아예 제대로 담기질 않은 것 같은데 나름대로 코드 실수를 찾아봐도 찾기가 어려워서 질문 드립니다.
참고로 책에서 그 다음 예외 처리에 대해서도 같은 에러가 발생합니다.

**Comment by shinsunyoung** [comment]
안녕하세요. GlobalExceptionHandler.java 코드를 똑같이 작성하셨는지 확인해보시면 좋을 것 같습니다.

https://github.com/shinsunyoung/springboot-developer/blob/main/appendixB/src/main/java/me/shinsunyoung/springbootdeveloper/config/error/GlobalExceptionHandler.java

**Comment by 9uiopa** [comment]
아, 파일 받아서 비교해보니까  핸들러는 같은데 ErrorResponse 쪽에 생성자 annotaion을 안적었네요. 감사합니다~
