### ISSUE TITLE
[Chapter 10] 10.4 서버 시작시 순환참조 발생

### ISSUE THREAD

**Issue by kwangsus** [shinsunyoung/springboot-developer#49]
![스크린샷 2024-02-13 212646 순환참조오류](https://github.com/shinsunyoung/springboot-developer/assets/73776010/28fb0c53-7745-4c6f-a7b4-d3fc8065420f)

10.3.7까지 진행후 실행하면 순환참조가 뜨는데요.. 비교해봤으나 차이점을 모르겠어서 질문드립니다 ㅠ
yml은 이상 없습니다!

https://github.com/kwangsus/spring-developer/tree/main/src/main/java/me/ks/springdeveloper

**Comment by shinsunyoung** [comment]
https://github.com/shinsunyoung/springboot-developer/blob/main/chapter10/src/main/java/me/shinsunyoung/springbootdeveloper/service/UserService.java

PasswordEncoder를 생성하는 방법이 다릅니다~!

**Comment by kwangsus** [comment]
아~~ 저걸 안바꿨네요 감사합니다! 잘되네요
