### ISSUE TITLE
[Chapter 10] 259p, 중간 그림 관련 질문 드립니다. 

### ISSUE THREAD

**Issue by ironwhale1014** [shinsunyoung/springboot-developer#50]
안녕하세요 

권한부여 코드 승인 타입에 대해 공부하는데 중간에 그림이 잘 이해가 안되서요 

아래 권한 요청 설명으로 보면 스프링 부터 서버가 권한서버(카카오나 구글)에 요청을 보내는 것이라 되어 있는데 

위에 그림에 1번 권한 요청은 리소스 오너 -> 애플리케이션 이부분에 권한 요청이라고 되어 있습니다. 

_**권한 요청의 설명과 위에 그림을 매칭 시키면 리소스 오너 = 스프링 부트 서버가 되고 애플리케이션 = 권한 서버가 됩니다.**_ 

근데 또 앞에 258페이지에는 리소스 오너 = 서비스 이용자 라고 되어 있어  좀 헷갈리는데 

그냥 권한 요청의 설명과 위에 그림을 매칭 시키는 방식으로 이해하면 되는건가요??

**Comment by shinsunyoung** [comment]
안녕하세요.

1. 권한 요청

사용자(리소스 오너)가 [OAuth 로그인] 같은 버튼을 누르면 애플리케이션에서는 인증 서버에게 요청을 보내게 됩니다.
이때 보내는 요청이 <권한 요청을 위한 파라미터 예>에 나와있는 것 처럼 /authorize 와 같은 path로 요청을 보내게 되는 것이고,

인증 서버에서는 요청을 받게 되면 2. 데이터 접근용 권한 부여 단계로 넘어가는 것입니다.

그렇기 때문에 리소스 오너 = 사용자, 애플리케이션 = 클라이언트 애플리케이션, 권한 서버 = 구글, 페이스북과 같은 OAuth 기능을 제공해주는 서버가 맞습니다. 혹시 더 이해 안되시는 것 있으면 알려주세요!

**Comment by ironwhale1014** [comment]
답변 감사합니다.
