### ISSUE TITLE
[Chapter 11] 서비스 배포후 404오류

### ISSUE THREAD

**Issue by melaminn38** [shinsunyoung/springboot-developer#52]
![1](https://github.com/shinsunyoung/springboot-developer/assets/141012319/cebc46d4-4a45-4abc-b779-c4bae54bc323)
![2](https://github.com/shinsunyoung/springboot-developer/assets/141012319/e6b9b1a1-0bde-4207-9ae4-085a11093a61)
![3](https://github.com/shinsunyoung/springboot-developer/assets/141012319/42eac27a-0acd-4e61-abfd-e8cfbb49af8e)
![4](https://github.com/shinsunyoung/springboot-developer/assets/141012319/b539c052-b711-4b87-85ea-845d0a443cb3)

어디서 문제가 있는지 모르겠네요...

**Comment by shinsunyoung** [comment]
안녕하세요~ 404 Whitelabel Error Page가 나오는게 정상입니다! /login으로 진입해보셔서 확인해보시겠어요?

**Comment by melaminn38** [comment]
확인했어요 해결했습니다!
