### ISSUE TITLE
[Chapter 10] 10.4 OAuth2 실행 테스트 관련 오류 질문

### ISSUE THREAD

**Issue by SummerToday** [shinsunyoung/springboot-developer#54]
10.4 OAuth2 실행 테스트를 해보니 리프레시 토큰은 개발자 도구를 통해 확인해보니 잘 들어가 있는데, 엑세스 토큰이 안들어가는 것 같습니다.. 그래서 글 수정, 삭제 로직도 제대로 작동을 하지 않습니다.. 어디가 문제일까요..?? 
깃허브 코드 첨부합니다. https://github.com/SummerToday/Blog_SpringProject.git

**Comment by shinsunyoung** [comment]
![image](https://github.com/shinsunyoung/springboot-developer/assets/42836576/8fd13cd3-4193-4ade-b7ad-e370b4bbca14)
안녕하세요! 제 컴퓨터에서는 잘 들어가는 것으로 보이는데요. 혹시 관리자 도구 - Application - Local Storage에서 못찾으신건가요?

수정/삭제가 안 되는 이유는 본인 글이 아닌 경우에는 불가능하게 예외로직을 작성했는데 그것 때문은 아닌지 확인 한 번만 부탁드리겠습니다!

**Comment by SummerToday** [comment]
보니까 html 파일의 스크립트 파일 참조하는 부분 경로가 잘못 설정되어 있어서 그 부분 수정하니 해결되었습니다!
근데 이제 다른 기능들 모두 구현은 되는데, 로그아웃을 누르면 로그인 페이지까지 리다이렉트도 잘 되는데 구글 로그인 버튼을 누르면 기존 로그인 정보로 자동으로 로그인이 계속 되는데, 왜 이러는건가요??

**Comment by shinsunyoung** [comment]
로그아웃 기능은 세션 기반 인증을 사용하는 것으로 추가한 기능이고, 책에서 토큰 기반 인증에서 로그아웃을 하기 위해 토큰을 직접 삭제했습니다. 요걸 구현해보시고 싶으시면 세션 기반 인증 로그아웃같이 검색하여 참고하셔서 구현해보셔도 좋을 것 같습니다(ex. https://upcurvewave.tistory.com/611)

**Comment by SummerToday** [comment]
주말인데도 이렇게 코멘트 남겨주셔서 감사합니다!
