### ISSUE TITLE
[Chapter 11] spring security 흐름 질문

### ISSUE THREAD

**Issue by kwangsus** [shinsunyoung/springboot-developer#56]
안녕하세요 책으로 잘 배우고 있습니다.

현재 자바 17, 스프링부트3.2.1 버전 사용중입니다.
로그인 이후 토큰 발급 순서가

로그인 -> OAuth2UserCustomService.loadUser에서 User 정보를 db에 저장 
로그인 성공시 : OAuth2SuccessHandler.onAuthenticationSuccess에서 로그인정보를 바탕으로 RefreshToken, AccessToken 생성 후 쿠키 및 db에 저장 후 리다이렉트

로그인 실패시 : 실행되는 함수 없음

이런 과정인것 같은데 현재 로그인 실패가 돼서 토큰 인증이 안되는 상황입니다. 그래서 디버깅을 하고 있는데 질문이 있습니다

1. 디버깅 하다보니 /article이든 어디든 무조건 validToken 검사를 하는데 이 검사를 하는 부분이 springconfig에 정의된 것 같은데 어느 부분인지 알고싶습니다.
2.  로그인 이후 인증서버에서 오는 1시간짜리 AccessToken이랑 위에서 구현해 만든 AccessToken과 다른점과 인증서버에서 오는데 따로 구현한 이유 궁금합니다
![스크린샷 2024-03-26 200936](https://github.com/shinsunyoung/springboot-developer/assets/73776010/57a92e60-5339-46c0-9bf7-9c4c93c99e5a)

**Comment by shinsunyoung** [comment]
안녕하세요

1. TokenAuthenticationFilter 에서 검사합니다. TokenAuthenticationFilter 는 WebOAuthSecurityConfig에 addFilterBefore(tokenAuthenticationFilter(), UsernamePasswordAuthenticationFilter.class)로 정의되어 있습니다.

2. OAuth2UserRequest에 들어있는 Access Token은 OAuth 로그인을 하는 주체(Google)로부터 사용자 정보를 가져오기 위해 필요한 토큰이고(토큰을 사용하는 곳: 인증 서버), 우리가 발급하는 Access Token은 클라이언트에서 애플리케이션에 요청을 할 때 사용하기 위한 정보가 담겨있는 토큰입니다(토큰을 사용하는 곳: 애플리케이션). 사용하는 용도가 다르기 때문에 별도로 구현하는 것이라고 이해하시면 됩니다!

추가로 궁금한 점 있으시면 코멘트 달아주세요. 감사합니다 🙇
