### ISSUE TITLE
[부록 A]  테스트(Title이 null체크,  길이체크) 중

### ISSUE THREAD

**Issue by leeseewoo** [shinsunyoung/springboot-developer#58]
Appendix A를 실행중
Test 실패합니다. 
마우스를 오버해보면 하기와 같이 표시가 되어,

첨부2와 같이 임의로 변경하였더니, Test가 정상적으로 수행되었습니다.

이게 정상적인 건가요?

![1](https://github.com/shinsunyoung/springboot-developer/assets/65908573/02c802fd-11c6-4be2-831c-59b2fc2e92d4)
![2](https://github.com/shinsunyoung/springboot-developer/assets/65908573/72eaf352-8988-4bb2-95c9-e97121380c6a)

**Comment by shinsunyoung** [comment]
안녕하세요, 5xxServerError가 아닌 BadRequest로 테스트가 성공해야 합니다. Validation이 제대로 적용되지 않은 것으로 보입니다 ㅠㅠ

**Comment by shinsunyoung** [comment]
안녕하세요. 오랜 기간 답변이 없어 이슈 닫아두도록 하겠습니다.
추가 질문 생기시면 re-open 해주시거나 새롭게 이슈 등록 부탁드리겠습니다! 😄
