### ISSUE TITLE
[Chapter 09] 교재 290p  context.petAuthentication() 실행하고 콘솔에서 result 값을 확인하는 그림이 있는데 어떻게 실해하는지 방법을 알려주세요

### ISSUE THREAD

**Issue by jslee912** [shinsunyoung/springboot-developer#59]
ch09 교재 290p  context.petAuthentication() 실행하고 콘솔에서 result 값을 확인하는 그림이 있는데 어떻게 실해하는지 방법을 알려주세요

**Comment by shinsunyoung** [comment]
안녕하세요, https://jojoldu.tistory.com/149 요 글 참고하시어 context.setAuthentication() 코드에 break point 잡으시고 OAuth 로그인 하시면 확인이 가능합니다
