### ISSUE TITLE
[Chapter 08] 스프링 시큐리티로 회원가입, 로그인/로그아웃

### ISSUE THREAD

**Issue by young5306** [shinsunyoung/springboot-developer#60]
안녕하세요,
8장의 회원가입, 로그인, 로그아웃을 구현하면서 어려운 점이 있어 질문드립니다!

pg217의 테스트를 실행하면서 회원가입 후 로그인을 보튼을 눌렀을 때, webSecurityConfig에 로그인 요청 성공시 이동할 페이지로 지정한 곳으로 이동되지 않습니다.

`http.formLogin((formLogin) -> formLogin
						.loginPage("/login")
						.defaultSuccessUrl("/content"));`

다음과 같이 content 뷰 페이지로 돌아가도록 지정했는데, 제대로 작동하지 않는 이유가 궁금합니다.

또한 h2-console에 접근하기 위해 다음과 같이 작성했는데, 연결 거부가 뜹니다. 코드에 문제가 있는건가요?

`http.authorizeHttpRequests((auth) -> auth
                        .requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll() // 정적 리소스로 요청이 들어오면 인증을 허가
                        .requestMatchers(PathRequest.toH2Console()).permitAll()
                        .requestMatchers("/signup", "/user", "/login").permitAll()
                        .anyRequest().authenticated()
        );`
![image](https://github.com/shinsunyoung/springboot-developer/assets/140944183/9019c3b8-9d91-4c8e-8faf-f40d21ea5307)

![image](https://github.com/shinsunyoung/springboot-developer/assets/140944183/917a0f49-2a3c-42a5-a1c2-012b1460f2a3)

[loginPractice.Zip](https://github.com/shinsunyoung/springboot-developer/files/15174397/loginPractice.Zip)

**Comment by shinsunyoung** [comment]
안녕하세요~! WebSecurityConfig.java 파일에 아래 코드를 추가해보시고 다시 확인해보시겠어요??

```
    @Bean
    public WebSecurityCustomizer configure() { // 스프링 시큐리티 기능 비활성화
        return (web) -> web.ignoring()
                .requestMatchers(toH2Console())
                .requestMatchers(
                        new AntPathRequestMatcher("/img/**"),
                        new AntPathRequestMatcher("/css/**"),
                        new AntPathRequestMatcher("/js/**")
                );
    }
```

**Comment by shinsunyoung** [comment]
오랫동안 추가 코멘트가 없어 이 이슈는 닫아두겠습니다. 추가로 문의 사항 생기시면 다시 열어주시거나 새 이슈로 등록 부탁드립니다!
