### ISSUE TITLE
[Chapter 11] 빌드 에러 발생

### ISSUE THREAD

**Issue by SummerToday** [shinsunyoung/springboot-developer#61]
빌드를 하는 도중 아래 오류가 발생합니다..
![image](https://github.com/shinsunyoung/springboot-developer/assets/88650436/28beacf8-7f36-473e-974c-912b58bae226)
build.gradle 문제인 것 같아 이것저것 고쳐보았는데도 해결이 안됩니다ㅜㅜ

깃에 올려놓은 코드 첨부합니다
https://github.com/SummerToday/Blog_SpringProject.git

--------------------------------------

현재 의존성을 implementation 'mysql:mysql-connector-java:8.0.33'과 같이 버전을 명시해서 수정하니 정상적으로 빌드가 되긴했습니다. 하지만 인텔리제이의 DB Browser의 콘솔에서 SELECT VERSION(); 명령어를 통해 mysql 버전을 확인해본 결과 8.0.35가 맞는데 8.0.35도 위와 같은 오류가 발생하고 8.0.34 버전도 같은 오류가 발생했습니다. 결국 8.0.33 버전으로 낮춰서 빌드해보니 정상적으로 빌드가 되긴 했는데, 원래는 8.0.35로 하면 정상적으로 빌드가 되야하는거 아닌가요?? 이 부분에 대해서 설명 좀 부탁드립니다..

감사합니다!

**Comment by shinsunyoung** [comment]
안녕하세요. https://mvnrepository.com/artifact/mysql/mysql-connector-java 를 보시면 가장 최근 버전이 8.0.33 입니다.
DB Browser의 콘솔에서 확인하신 버전은 데이터베이스 엔진 버전이고, 이건 라이브러리 버전이라 버전이 다릅니다!
