### ISSUE TITLE
[Chapter 06] Create, Update에서 값을 반환하는 이유

### ISSUE THREAD

**Issue by SeongGwangJu** [shinsunyoung/springboot-developer#68]
[질문 1]
(쳅터 6까지의) 교재 코드에서 추가,수정 API는 Article 객체를 반환하는데요.
짧은 생각으로는 클라이언트가 응답 코드만 받고 값은 받지 않더라도 문제가 없을 것 같은데요.(추가/수정 후 GET요청을 한다는 전제 하에는)
새롭게 응답을 하는 이유가 궁금합니다. 
(관례인걸까요? 아니면, 클라이언트에서 GET 요청을 추가로 하지 않기 위함일까요?)

[질문 2]
질문1과 이어지는 질문인데요, 

교재 코드에서 GET요청시에는 ArticleResponse라는 DTO로 반환하고 있는데요.

POST나 PUT에서는 따로 감싸지 않아도 되나요? 어차피 클라이언트가 준 값이기 때문에 구태여 DTO로 옮길 필요가 없는 걸까요?

**Comment by shinsunyoung** [comment]
안녕하세요

질문 1.
클라이언트에서 추가, 수정 시에 다시 조회 API를 요청하지 않게 하기 위해 응답 객체를 반환하는 경우가 있고, RESTful한 API를 설계할 때 응답 본문을 넘겨주는 것이 일반적인 관례입니다. (참고 링크: https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api의 Updates & creation should return a resource representation 참고. 여기에서는 Location을 응답해야 한다고 나와있긴 하지만 Location을 넘겨주는 것이 이론상 맞으나 보통 Location보다는 응답 객체를 반환하는 경우를 더 많이 보아서 응답 객체를 반환하게 예제코드를 구성하였습니다.)

질문 2.
DTO를 만들어서 반환해도 상관 없습니다. 실제로 저도 개발할 땐 응답 객체로 DTO를 반환하도록 구현하는 편이지만, 책에서 모두 DTO로 반환하도록 구성하면 너무 많은 코드가 반복되기 때문에 엔티티를 직접 반환하게 구현해두었다고 생각해주시면 될 것 같습니다.

더 궁금한 점 있으면 댓글 달아주세요. 감사합니다~!!

**Comment by SeongGwangJu** [comment]
이해되었습니다. 감사합니다!
