### ISSUE TITLE
[CH9]실행을 했을때 빈 순환 오류가 납니다

### ISSUE THREAD

**Issue by nnnnnnniam1** [shinsunyoung/springboot-developer#7]
┌─────┐
|  webOAuthSecurityConfig defined in file [C:\Users\daggg\Downloads\sample\projectIBDA\out\production\classes\com\IBDA\config\WebOAuthSecurityConfig.class]
↑     ↓
|  userService defined in file [C:\Users\daggg\Downloads\sample\projectIBDA\out\production\classes\com\IBDA\service\UserService.class]
└─────┘

둘이 순환을 한다는데 userService에서는 webOAuthSecurityConfig를 어디서 사용했는지 모르겠습니다.

**Comment by shinsunyoung** [comment]
안녕하세요! 코드를 제공해주시면 보다 정확한 답변을 해드릴 수 있을 것 같습니다! 혹시 깃허브에 코드를 올려주실 수 있으신가요?

**Comment by MunseopLim** [comment]
저도 같은 경우가 있었는데 혹시 UserService 구현하실 때 이렇게 사용하셨는지 한번 확인해 보세요.
```
public class UserService {
    private final UserRepository userRepository;
    private final BCryptPasswordEncoder bCryptPasswordEncoder;

    public Long save(AddUserRequest dto) {
        return userRepository.save(User.builder()
            .email(dto.getEmail())
            .password(bCryptPasswordEncoder.encode(dto.getPassword()))
            .build()).getId();
    }
```
copilot을 쓰다보니 저렇게 되어 있는지도 모르고 지나갔었는데 훑어보니 그렇더라구요 ㅜㅜ
책 내용대로 다시 수정하니 잘 되었던 기억이 있습니다.
```
public class UserService {
    private final UserRepository userRepository;

    public Long save(AddUserRequest dto) {
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        return userRepository.save(User.builder()
            .email(dto.getEmail())
            .password(encoder.encode(dto.getPassword()))
            .build()).getId();
    }
```

**Comment by nnnnnnniam1** [comment]
저도 책을 다시 찬찬히 보면서 해결했습니다
