### ISSUE TITLE
Chapter7 WebSecurityConfig 페이지 SecurityFilterChain formLogin() 오류

### ISSUE THREAD

**Issue by BarBamBa** [shinsunyoung/springboot-developer#9]
Spring Security 버전이 올라가며

WebSecurityConfig 에서 시큐리티 코드 사용 방법이 많이 달라진 것 같은데

최신버전에서 사용 할 수 있는 코드도 알려주실 수 있을까요?

**Comment by shinsunyoung** [comment]
#5 이 이슈 참고해주시면 될 것 같습니다! 혹시나 이후에도 해결되지 않는다면 알려주세요. 감사합니다!

**Comment by BarBamBa** [comment]
해결이 된 것 같습니다 감사합니다
